name: "test"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: get version
      id: version
      uses: ./
      with:
        path: 'package.json'
        prop_path: 'version'
    - run: echo ${{steps.version.outputs.prop}}

    - name: get nested json property
      id: get_json_property
      uses: ./
      with:
        path: 'package.json'
        prop_path: 'scripts.format'
        prop_path2: 'version'

    - run: echo "prop = ${{ steps.get_json_property.outputs.prop }}"
    - run: echo "prop2 = ${{ steps.get_json_property.outputs.prop2 }}"

    - name: get item in array
      id: version
      uses: ./
      with:
        path: 'package.json'
        prop_path: 'keywords[0]'
    - run: echo ${{steps.version.outputs.prop}}